base_main/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	# admin
    path('c0d3b453/', admin.site.urls),
    # home
    path('', include('home.urls')),
    # apps
    path('self-assessment/', include('portal_risk.urls')),
    path('file-a-claim/', include('claim.urls')),
]
# serve the uploaded media files using the development server
if settings.DEBUG:
    # urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

claim/urls.py
from django.urls import path

from . import views

app_name = 'claim'

urlpatterns = [
	path('', views.add_claim, name='path_to_claim')
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
	path('', views.home_page, name='path_to_home'),
	path('contact/', views.contact_page, name='path_to_contact'),
]

claim/models.py
from django.db import models

# Create your models here.
TRUE_FALSE_CHOICES = (
	(True, 'Yes'),
	(False, 'No'),
)

MANUFACTURED_YEAR_CHOICES = (
	('1970', '1970'),
	('1980', '1980'),
	('1990', '1990'),
	('2000', '2000'),
	('2010', '2010'),
	('2020', '2020'),
)

CAR_MODEL_CHOICES = (
	('toyota', 'Toyota'),
	('mazda', 'Mazda'),
	('renault', 'Renault'),
	('ford', 'Ford'),
	('dansun', 'Datsun'),
)

class FileClaimVehicleTheft(models.Model):
	name = models.CharField(max_length=100, db_index=True)
	occupation = models.CharField(max_length=50, db_index=True)
	phone_number = models.IntegerField(db_index=True)
	email = models.EmailField(max_length=50, db_index=True)

	vehicle_registration = models.CharField(max_length=100, db_index=True)
	vehicle_make = models.CharField(max_length=200, choices=CAR_MODEL_CHOICES, db_index=True, default='')
	manufactured_year = models.CharField(max_length=200, choices=MANUFACTURED_YEAR_CHOICES, db_index=True)

	hp_loan_agreements = models.BooleanField(default=True)
	# hp_loan_agreements = models.CharField(max_length=200, choices=TRUE_FALSE_CHOICES, db_index=True, default='')
	
	class Meta:
		ordering = ('name',)
		verbose_name = 'car_theft_claim'
		verbose_name_plural = 'car_theft_claims'

	def __str__(self):
		return self.name

claim/forms.py
from django.forms import ModelForm

from .models import FileClaimVehicleTheft
# Create your forms here.
class FileClaimVehicleTheftForm(ModelForm):
	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.fields['name'].widget.attrs.update({
			'placeholder': 'Full Name',
			'class': 'form-control'
		})
		self.fields['occupation'].widget.attrs.update({
			'placeholder': 'Occupation/Job',
			'class': 'form-control'
		})
		self.fields['phone_number'].widget.attrs.update({
			'placeholder': 'Phone Number...',
			'class': 'form-control'
		})
		self.fields['email'].widget.attrs.update({
			'placeholder': 'E-Mail Address',
			'class': 'form-control'
		})
		self.fields['vehicle_registration'].widget.attrs.update({
			'placeholder': 'Registration Number',
			'class': 'form-control'
		})
		self.fields['vehicle_make'].widget.attrs.update({
			'placeholder': 'Make',
			'class': 'form-control'
		})
		self.fields['manufactured_year'].widget.attrs.update({
			'placeholder': 'Year Vehicle Was Manufactured',
			'class': 'form-control'
		})
		self.fields['hp_loan_agreements'].widget.attrs.update({
			# 'placeholder': 'Boolean',
			'class': 'form-control'
		})
	class Meta:
		model = FileClaimVehicleTheft
		fields = '__all__'




	# TRUE_FALSE_CHOICES = (
	# 	(True, 'Yes'),
	# 	(False, 'No'),
	# )

	# MANUFACTURED_YEAR_CHOICES = (
	# 	(1970, '1970'),
	# 	(1980, '1980'),
	# 	(1990, '1990'),
	# 	(2000, '2000'),
	# 	(2010, '2010'),
	# 	(2020, '2020')
	# )

	# CAR_MODEL_CHOICES = (
	# 	('toyota', 'Toyota'),
	# )

	# name = forms.CharField(required=False, max_length=100,
		# widget=forms.TextInput(attrs={'placeholder': 'Full Name', 'class' : 'form-control'}))
	# occupation = forms.CharField(required=False, max_length=100,
	# 	widget=forms.TextInput(attrs={'placeholder': 'Occupation', 'class' : 'form-control'}))
	# phone_number = forms.IntegerField(required=False,
	# 	widget=forms.NumberInput(attrs={'placeholder': 'Enter Your Phone Number', 'class' : 'form-control'}))
	# email = forms.EmailField(required=False,
	# 	widget=forms.TextInput(attrs={'placeholder': 'Enter Your E-Mail', 'class' : 'form-control'}))

	# vehicle_registration = forms.CharField(required=False, max_length=100,
	# 	widget=forms.TextInput(attrs={'placeholder': 'Vehicle Registration Number', 'class' : 'form-control'}))

	# vehicle_make = forms.ChoiceField(required=True, choices=CAR_MODEL_CHOICES, initial='',
	# 	widget=forms.Select(attrs={'class' : 'form-control'}))
	# manufactured_year = forms.ChoiceField(required=True, choices=MANUFACTURED_YEAR_CHOICES, initial='',
	# 	widget=forms.Select(attrs={'class' : 'form-control'}))

	# hp_loan_agreements = forms.ChoiceField(required=True, choices=TRUE_FALSE_CHOICES, label="Some Label", initial='',
	# 	widget=forms.Select(attrs={'class' : 'form-control'}))

claim/views.py
from django.shortcuts import render
from django.contrib import messages

# pdf
import weasyprint
from django.template.loader import render_to_string
from django.http import HttpResponse
from django.conf import settings
from django.shortcuts import get_object_or_404

from .forms import FileClaimVehicleTheftForm
from .models import FileClaimVehicleTheft

# Create your views here.
def add_claim(request):
	# theft_form = FileClaimVehicleTheftForm(request.POST)

	if request.method == 'POST':
		theft_form = FileClaimVehicleTheftForm(request.POST)

		if theft_form.is_valid():
			filing=theft_form.save()

			filing = get_object_or_404(FileClaimVehicleTheft, id=2)
			html = render_to_string('claim/cars/pdf.html', {'filing': filing})
			response = HttpResponse(content_type='application/pdf')
			response['Content-Disposition'] = 'filename="theft_claim.pdf"'
			weasyprint.HTML(string=html).write_pdf(
				response, stylesheets=[weasyprint.CSS(settings.STATIC_ROOT + "/css/pdf.css")])
			return response
	else:
		theft_form = FileClaimVehicleTheftForm()

	context = {
		'theft_form': theft_form
	}
	return render(request, 'claim/cars/car_claim.html', context)

claim/templates/claim/cars/car_claim.html
{% extends "base.html" %}

{% block title %}
	File a Car-Theft Claim
{% endblock title %}

{% block content %}
	<div id="whole">
		<div class="container-fluid contact-section-padding">
			<div class="row align-items-center">
				<div class="col-lg-7 mb-5 mb-lg-0">
					<div class="card border-0 shadow-sm">
						<div class="card-body p-5 border-top border-primary border-md">
							<h2 class="lined"><strong>Car Theft Claim</strong></h2>
							<p class="text-muted">File a car-theft claim</p>
							<form method="POST" action="{% url 'claim:path_to_claim' %}">
								{% csrf_token %}
								<div class="row">
			            <div class="form-group col-lg-6 mb-4">
			              {{ theft_form.name }}
			            </div>
			            <div class="form-group col-lg-6 mb-4">
			              {{ theft_form.occupation }}
			            </div>
			            <div class="form-group col-lg-6 mb-4">
			              {{ theft_form.phone_number }}
			            </div>
			            <div class="form-group col-lg-6 mb-4">
			              {{ theft_form.email }}
			            </div>
			            <div class="form-group col-lg-6 mb-4">
			            	<text class="text-success">Registration Number</text>
			              {{ theft_form.vehicle_registration }}
			            </div>
			            <div class="form-group col-lg-6 mb-4">
			            	<text class="text-success">Vehicle Make</text>
			            	{{ theft_form.vehicle_make }}
			            </div>
			            <div class="form-group col-lg-12 mb-4">
			            	<text class="text-success">Driving Experience in Years</text>
			              {{ theft_form.manufactured_year }}
			            </div>
			            <div class="form-group col-lg-12">
			              <input class="btn btn-info btn-block" type="submit"></input>
			            </div>
		          	</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock content %}

claim/templates/claim/cars/pdf.html
<html>
<body>
  <h1>Jubilee Interview: Claim Filing App | Car Theft </h1>
  <p>Please Note That:-</p>
  <p>
    It is necessary that great care should be taken in completing this Form and the information given therein should be strictly accurate, irrespective of whether it is in your favour or otherwise. You should not make any payment offer or promise of any payment or admit liability in anyway, as by so doing you may prejudice your position and make settlement a difficult matter.
  </p>
  <hr>
  <br>
  <h3>Personal Information</h3>
  <p>
    Name of Insured: {{ filing.name }}<br>
    Occupation: {{ filing.occupation }}<br>
    Email Address: {{ filing.email }}<br>
    Phone Number: {{ filing.phone_number }}
  </p>

  <h3>Vehicle Particulars</h3>
  <p>Registration No: {{ filing.vehicle_registration }}</p>
  <p>Vehicle Make: {{ filing.vehicle_make }}</p>
  <p>Model: {{ filing.phone_number }}</p>
  <p>Year Manufactured: {{ filing.manufactured_year }}</p>
  <p>
    Is the vehicle the subject of a hire purchase or loan agreement?
    <br>
    {{ filing.hp_loan_agreements }}  
  </p>
</body>
</html>