base_main/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	# admin
    path('c0d3b453/', admin.site.urls),
    # home
    path('', include('home.urls')),
    # apps
    path('self-assessment/', include('portal_risk.urls')),
    path('file-a-claim/', include('claim.urls')),
]
# serve the uploaded media files using the development server
if settings.DEBUG:
    # urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
	path('', views.home_page, name='path_to_home'),
	path('contact/', views.contact_page, name='path_to_contact'),
]

home/forms.py
from django import forms

# Create your forms here.
class ContactUsForm(forms.Form):
	SENDER_CHOICES = (
		('cus', 'Customer'),
		('oth', 'Other'),
	)
	REC_CHOICES=(
		('rec', 'Recommendation'),
		('cmp', 'Complaint'),
	)

	first_name = forms.CharField(required=False, max_length=100,
		widget=forms.TextInput(attrs={'placeholder': 'First Name...', 'class' : 'form-control'}))
	last_name = forms.CharField(required=False, max_length=100,
		widget=forms.TextInput(attrs={'placeholder': 'Last Name...', 'class' : 'form-control'}))
	sender = forms.ChoiceField(required=True, choices=SENDER_CHOICES,
		widget=forms.Select(attrs={'class' : 'form-control'}))
	recom = forms.ChoiceField(required=True, label='recom', choices=REC_CHOICES,
		widget=forms.Select(attrs={'class' : 'form-control'}))
	phone_number = forms.IntegerField(required=False,
		widget=forms.NumberInput(attrs={'placeholder': 'Phone Number...', 'class' : 'form-control'}))
	email = forms.EmailField(required=True,
		widget=forms.TextInput(attrs={'placeholder': 'E-Mail...', 'class' : 'form-control'}))
	subject = forms.CharField(required=True, max_length=100,
		widget=forms.TextInput(attrs={'placeholder': 'Subject...', 'class' : 'form-control'}))
	message = forms.CharField(required=True, max_length=500,
		widget=forms.Textarea(attrs={'placeholder': 'Enter Message Here...', 'class' : 'form-control'}))

home/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect

from .forms import ContactUsForm

# Create your views here.
def home_page(request):

	context = {
	}
	return render(request, 'home/pages/home.html', context)

def contact_page(request):
	if request.method == 'POST':
		form = ContactUsForm(request.POST)
		if form.is_valid:
			return HttpResponseRedirect('/thanks/')
	else:
		form = ContactUsForm()

	context = {
		'contact_form': form
	}
	return render(request, 'home/pages/contact.html', context)

home/templates/home/content/plugins/navigation.html
<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
	<div class="container">
		<a class="navbar-brand js-scroll-trigger" href="{% url 'home:path_to_home' %}">Home</a>
		<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">Menu
			<i class="fas fa-bars"></i>
		</button>
		<div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#">Self-Assessment</a></li>
        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#">File Claim</a></li>
      </ul>
    </div>
  </div>
</nav>
<!-- Masthead-->
<header class="masthead">
  <div class="container d-flex h-100 align-items-center">
    <div class="mx-auto text-center">
      <h1 class="mx-auto my-0 text-uppercase">Interview Prototypes</h1>
      <h2 class="text-white-50 mx-auto mt-2 mb-5">
        Django/Python BackEnd
        <br>
        Plus:
        <a href="https://www.creativejayax.co.ke/">Sample 1</a>
        <a href="https://www.techdimensional.com/">Sample 2</a>
        <a href="https://savannahtraining.solutions/">Sample 3</a>
        <a href="https://www.arkshelters.co.ke/">Sample 4</a>
        <a href="http://www.reocommfoundation.org/">Sample 5</a>
      </h2>
    </div>
  </div>
</header>